# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: Norsk Matematisk Forening
email: post@matematikkforeningen.no
description: >-
  Norsk matematisk forening (NMF) — promoting mathematics in Norway since 1918. News, events, publications and competitions for researchers, students and teachers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://matematikkforeningen.no
twitter_username: nmf_no
github_username:  matematikkforeningen

# Build settings
plugins:
  - jekyll-feed

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Exclude from processing
exclude:
  - admin/README.md
  - admin/TEMPLATE-nyhet.md
  - admin/TEMPLATE-arrangement.md
  - admin/TEMPLATE-infomat.md
  - admin/filstruktur.md
  - README.md
  - docs/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - node_modules/
