# Production:
#backend:
#  name: github
#  repo: ballerin/nmf-website
#  branch: main
#  auth_endpoint: /auth
#  base_url: https://nmf-oauth.ballerin.workers.dev

# Local testing:
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

site_url: https://nmf-website.pages.dev
display_url: https://nmf-website.pages.dev

locale: 'en'

collections:
  - name: "news"
    label: "News"
    folder: "_posts/nyheter"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    preview_path: "news/{{year}}/{{month}}/{{day}}/{{slug}}"
    sortable_fields: ["date"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "nyheter_template" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Categories", name: "categories", widget: "list", default: ["news"] }

  - name: "events"
    label: "Events"
    folder: "_posts/arrangementer"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    preview_path: "arrangement/{{year}}/{{month}}/{{day}}/{{slug}}"
    sortable_fields: ["date"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "activity_post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Start Date", name: "start-date", widget: "datetime", required: false }
      - { label: "End Date", name: "end-date", widget: "datetime", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Categories", name: "categories", widget: "list", default: ["arrangement"] }

  - name: "infomat"
    label: "INFOMAT"
    folder: "_posts/infomat"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    preview_path: "infomat/{{year}}/{{month}}/{{day}}/{{slug}}"
    sortable_fields: ["date"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "infomat_template" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Categories", name: "categories", widget: "list", default: ["infomat"] }
